LICENSE
readme.md
setup.py

Add badges

---

src/conduit/auth/__init__.py
src/conduit/auth/models.py
src/conduit/auth/tests/test_auth_views.py
src/conduit/auth/views.py
src/conduit/conftest.py
src/conduit/scripts/tests/test_drop_tables.py
src/conduit/scripts/tests/test_populate.py
src/conduit/tests/postman/run-postman-tests.sh

Had to rewrite the db test setup a bit, should be more future proof now.

Add /api/users/login endpoint

---

Pipfile
Pipfile.lock
src/conduit/auth/models.py
src/conduit/auth/tests/test_auth_views.py
src/conduit/auth/tests/test_user_model.py
src/conduit/auth/views.py
src/conduit/migrations/versions/17de12da1127_users.py
src/conduit/profile/models.py
src/conduit/profile/tests/test_profile_model.py
src/conduit/profile/views.py
src/conduit/tag/views.py

TypeDicts are coming in Python 3.8: https://www.python.org/dev/peps/pep-0589/
But we can already use them in Python 3.7 with the recent releases of mypy!

Use TypedDict instead of pydantic for declaring response schema

---

.heroku/release.sh
Makefile
alembic.ini
etc/development.ini
etc/production.ini
etc/test.ini
src/conduit/__init__.py
src/conduit/conftest.py
src/conduit/migrations/README.md
src/conduit/migrations/env.py
src/conduit/scripts/tests/test_drop_tables.py

This replaces #25 due to a CI issue.

Reduce duplication in alembic configuration

---

src/conduit/tests/test_check_db_migrated.py

The existing tests for check_db_migrated were hard to understand, as
they relied heavily on mocking out parts of the Pyramid and alembic
internals. They effectively tested the implementation of the
`check_db_migrated` function, rather than the outcomes. This change
introduces a new local fixture which downgrades the structure of
the test database for one test, allowing for tests to run in the
context of an outdated database.
The existing tests for `check_db_migrated` are then replaced with simple
invokations of `bootstrap()`, which causes `check_db_migrated` to be
called by the app startup (as `SKIP_CHECK_DB_MIGRATED` is not given).
The tests assert that the check is indeed called by `bootstrap` and
that `sys.exit` is either called or not, depending on which `db`
fixture is in use.

Switch mock based tests of check_db_migrated to functional tests

---

Pipfile.lock

Closes https://github.com/niteoweb/pyramid-realworld-example-app/issues/14.

Upgrade to latest pyramid_heroku to use sayanarijit/expandvars

---

.pre-commit-config.yaml
Pipfile
Pipfile.lock

add bandit security checker to pre-commit

---

.circleci/config.yml
Pipfile.lock
runtime.txt
src/conduit/article/models.py
src/conduit/auth/models.py

Also update the models to be compatible with the new flake8.

Upgrade python and python packages

---

.gitignore
poetry.lock
pyproject.toml
src/conduit/article/views.py
src/conduit/auth/views.py
src/conduit/comment/views.py

Refs https://github.com/Pylons/pyramid_openapi3/pull/60

Upgrade to pyramid_openapi 0.5.0b3

---

poetry.lock
pyproject.toml

To test the new `extract_errors` function.

Upgrade to latest pyramid_openapi3 beta

---

poetry.lock

Ref: https://github.com/niteoweb/operations/issues/1232

Update Python packages

---

.circleci/config.yml
Dockerfile
docker-entrypoints/README.md
docker-entrypoints/develop.sh
docker-entrypoints/run.sh
docker-entrypoints/test.sh
shell.nix

- Separate develop from test dependencies
- Use entrypoints to run CI/CD tests
- Fix https://github.com/niteoweb/pyramid-realworld-example-app/issues/88

Improve docker entrypoints

---

poetry.lock
src/conduit/tests/postman/run-postman-tests.sh

Ref: https://github.com/niteoweb/operations/issues/1232

Upgrade Python Packages

---

.github/workflows/poetry-update.sh
.github/workflows/poetry-update.yml

Auto update python packages via github action.

Auto update python packages.

---

etc/production.ini
poetry.lock

Refs https://github.com/niteoweb/pyramid-realworld-example-app/issues/127

Use the new pyramid_heroku.host tween to add support for AutoIdle

---

etc/production.ini
poetry.lock
src/conduit/comment/__init__.py
src/conduit/comment/models.py
src/conduit/comment/tests/test_comment_views.py
src/conduit/comment/views.py
src/conduit/conftest.py

Refs https://github.com/Pylons/pyramid_openapi3/issues/21

Use latest pyramid_openapi3 to get endpoint validation

---

.circleci/config.yml
Makefile
etc/production.ini
etc/test.ini
poetry.lock
src/conduit/__init__.py
src/conduit/conftest.py
src/conduit/scripts/drop_tables.py
src/conduit/tests/test_check_db_migrated.py

Using `global_config` / `options` is not meant for what we are using it for. Let's clean things up.

Cleanup SKIP_CHECK_DB_MIGRATED

---

.github/scripts/update_deps.sh
.github/workflows/update_deps.yml

`poetry lock` only updates the `poetry.lock` file without installing the
dependencies.

Use `poetry lock` instead of `poetry update`

---

readme.md
shell.nix

Support Python 3.9

---

readme.md

- Add missing step to activate the virtual environment
- Clarify that pre-requisites are first installed, then the app

Improve flow of documentation to get started.

---

.github/workflows/reviewapp_test.yml
.heroku/release.sh
Makefile
poetry.lock
pyproject.toml
readme.md

Refs https://github.com/teamniteo/operations/issues/1344

Rename niteoweb -> teamniteo
